import { Inter } from "next/font/google";
import { Provider } from "./Context/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
<<<<<<< HEAD
  title: "GOING TO CHANGES IF IT WORKS",
=======
  title: "Portfolio",
>>>>>>> 97cc038b8e86d1eebcf2c0cd603e2a78cc42d737
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
